name: Continuous Deployment Production

on:
  workflow_dispatch:

jobs:
  Provision:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true   
    - name: Set subscription
      uses: Azure/powershell@v1
      with:
        inlineScript: az account set --subscription be3a8af9-08bd-46b0-a8b5-803a2799799d
        azPSVersion: latest
    - name: Remove existing resource group
      uses: Azure/powershell@v1
      with:
        inlineScript: Get-AzResourceGroup -Name iotservice-production | Remove-AzResourceGroup -Force
        azPSVersion: latest
    - name: Create resource group
      uses: Azure/powershell@v1
      with:
        inlineScript: az group create --name iotservice-production --location uksouth
        azPSVersion: latest
    - name: Create IoT hub
      uses: Azure/powershell@v1
      with:
        inlineScript: az iot hub create --resource-group iotservice-production --sku F1 --partition-count 2 --name iotHub
        azPSVersion: latest
    - name: Register IoT devices
      uses: Azure/powershell@v1
      with:
        inlineScript: az iot hub device-identity create --device-id sensor-one --hub-name iotHub
                      az iot hub device-identity create --device-id sensor-two --hub-name iotHub

                      az iot hub device-identity create --device-id actuator-one --hub-name iotHub
                      az iot hub device-identity create --device-id actuator-two --hub-name iotHub
        azPSVersion: latest
    - name: Create storage account
      uses: Azure/powershell@v1
      with:
        inlineScript: az storage account create --name iotstorage --resource-group storage-resource-group --location uksouth --sku Standard_RAGRS --kind StorageV2
        azPSVersion: latest
    - name: Create container
      uses: Azure/powershell@v1
      with:
        inlineScript: az ad signed-in-user show --query objectId -o tsv | az role assignment create --role "Storage Blob Data Contributor" --assignee @- \
          --scope "/subscriptions/be3a8af9-08bd-46b0-a8b5-803a2799799d/resourceGroups/iotservice-production/providers/Microsoft.Storage/storageAccounts/iotstorage"

          az storage container create --account-name iotstorage --name virtualdevices --auth-mode login
        azPSVersion: latest

  upload:

    runs-on: ubuntu-latest

    steps:
    - name: Create APP.zip using zip-files
      run: |
        zip-files --auto-root --outfile APP.zip soil-moisture-sensor/app.py
    - name: Upload zip to conatiner
      uses: Azure/powershell@v1
      with:
        inlineScript: az storage blob upload --account-name iotstorage --container-name <container> --name app --file APP.zip --auth-mode login
        azPSVersion: latest