name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Integrate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest and report coverage
      run: |
        pytest --cov-report term-missing --cov=actuator_one_app --cov=actuator_two_app --cov=sensor_one_app --cov=sensor_two_app --cov-fail-under=75
    - name: Check linting with pylint
      run: |
        pylint virtualdevices --exit-zero
    - name: Analyse code with radon cyclomatic complexity
      run: |
        radon cc virtualdevices -a