name: Continuous Deployment Acceptance

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  Deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Install zip-files
      run: |
        python -m pip install --upgrade pip
        pip install zip-files
    - name: Create virtualdevices.zip
      uses: papeloto/action-zip@v1
      with:
        files: devices/
        dest: virtualdevices.zip
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true   
    - name: Upload zip to conatiner
      uses: Azure/powershell@v1
      with:
        inlineScript: az storage blob upload --account-name iotstorage --container-name virtualdevices --name devices --file virtualdevices.zip --auth-mode login
        azPSVersion: latest