name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
    - name: Check linting with pylint
      run: |
        pylint soil-moisture-sensor/app.py soil-moisture-sensor/test_app.py --exit-zero
    - name: Analysing the code with radon cyclomatic complexity
      run: |
        radon cc soil-moisture-sensor/app.py soil-moisture-sensor/test_app.py -a
    - name: pytest coverage
      run: |
        pytest --cov=myproj tests/
    - name: Report test coverage
      run: |
        coverage report -m --fail-under=75 soil-moisture-sensor